### ISSUE TITLE
How to implement LSP for a multi-language kernel (SoS)?

### ISSUE THREAD

**Issue by BoPeng** [krassowski/jupyterlab-lsp#282]
Many thanks for your great work on language server support. I have just tried `jupyterlab-lsp`, which works great for `Python` and `R`, but unfortunately does not work for a multi-language [kernel SoS](https://github.com/vatlab/sos-notebook) that I have developed.

The idea behind of SoS is that it is a superkernel that sits between frontend and other kernels (see [this illustration](https://vatlab.github.io/sos-docs/) for details). It allows the use of multiple kernels in one notebook (through [sos-notebook](https://github.com/vatlab/sos-notebook) for classic jupyter and [jupyterlab-sos](https://github.com/vatlab/jupyterlab-sos) for jupyterlab), and allows [data exchange  among live kernels](https://vatlab.github.io/sos-docs/doc/user_guide/exchange_variable.html).

The reason why `jupyterlab-lsp` does not work with SoS is simple: it does not know what language SoS is. If we are to solve this problem, there needs to be some way for SoS to notify `jupyterlab-lsp` the language used for each cell. I can work at both the frontend and backend (e.g. write a language server for SoS), but I am not sure if cell-level language support is at all possible with `jupyterlab-lsp`. I would appreciate any insight from the developers if and how this can be done. Thanks.

**Comment by bollwyvl** [comment]
Yeah, the Language Server Protocol Specification doesn't say anything about multi-language documents, so we're kinda shooting in the dark here. Further, basically 0 language servers care about Jupyter's JSON format, or any special syntax kernel authors have added on top of their host language(s).

Our detection is currently based on existing Jupyter approaches like file extension sniffing, contents manager introspection, or in the case of notebooks, the kernel and or notebook metadata. If everything is just `sos`, we can't do much for you, nor do we offer many hooks into this system at this point.

Presently, we _do_ handle a small number of transclusions on the front-end, on a kernel-by-kernel basis, and it's rather deeply embedded inside the code. #191 discusses some approaches on how to normalize this, as a set of regular expressions + templates, or maybe some portable grammar and declarative transformation rules. If that's adopted, whether it's handled on the server side or the client side, there will be some hooks to extend it, ideally without having to rebuild the client (ha).

In a related effort, #268 (rough draft of an implementation on #278) suggests changing `jupyter_lsp` into a kernel, which handles all the management of language servers. If that approach is adopted, and your kernel supports kernel comms, you might be able to reuse the machinery there and offer your own solution... while that PoC presently treats the language server kernel as a singleton, it's important to me to _not_ inject more "our way or the highway" pieces into the architecture: even for a single language server kernel implementation, it is important to be able to launch multiple instances that handle different documents, again without restarting your whole system.

However, as you've created a multi-language kernel with a special syntax, you've basically created a new language, which is certainly not unique: `allthekernels`, `pidgy`, `metakernel` are all in the same boat, protocol-and-bits-on-disk-wise. In all these cases, you might end up having to create a multi-language Language Server. There are a number of toolkits for different languages for doing so, e.g. [pygls](https://github.com/openlawlibrary/pygls) or [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node), which might then in turn have to handle spinning up _other_ language servers, as you _really_ don't want to be writing all these things yourself. Costs aside, an investment in writing a Language Server can pay dividends through usability in any Language Server client.

Finally, there are also a number of upstream discussions occurring around this that may be worth your time to peruse:
- https://github.com/jupyterlab/team-compass/issues/67
- https://github.com/jupyter/enhancement-proposals/pull/26

**Comment by krassowski** [comment]
Just super fast thought from me: we may want to suport this case and it would be super easy if we settle on per-cell language definitions, but it requires a longer discussion and a consensu in the wider  Jupyter community.

**Comment by rezaeir** [comment]
@krassowski I think if lsp had this per-cell language definition it could work with SoS with much work on the SoS side because SoS kernel could be treated as another python kernel. Am I wrong? @BoPeng

**Comment by BoPeng** [comment]
The problem could potentially be solved at the backend or frontend level.

If I am to implement an sos-language-server, it will of course try to start and use other language servers and act as a proxy. However, the language server protocol might not allow the passing of meta information to the server, so the sos language server might not be able to know the language of the content being passed. Hopefully the situation is not as bad as @bollwyvl said, "shooting in a dark".

It appears easier, and cleaner to implement this at the frontend level since `jupyterlab-lsp` is designed to work with multiple language servers anyway. It should be good enough for `jupyterlab-lsp` to know which language server to talk to at the cell level. SoS currently has some customized messages for changing cell level kernel (e.g. https://github.com/vatlab/jupyterlab-sos/blob/master/src/index.ts#L497), so it could be quite trivial, as @krassowski pointed out, if `jupyterlab-lsp` provides a hook/api for `jupyterlab-sos` to dynamically change the language of the kernel. I can work on a PR if this is allowed by the architecture, and acceptable to the team.

**Comment by bollwyvl** [comment]
> However, the language server protocol might not allow the passing of meta information to the server, 

>  lsp had this per-cell language definition

> language server protocol might not allow the passing of meta information to the server

I wouldn't hold your breath trying to get changes into LSP! I may be very mistaken, but you'd have to make the case in such pitches very strongly that it would benefit microsoft and vscode pretty directly, and probably land some reference implementation there.

> per-cell language definitions

While useful, this doesn't solve the larger problem of per-token transclusions, e.g. line magics, or query languages embedded in strings (#197). Further, this would probably require a breaking change to `nbformat`, and probably the jupyter kernel messaging protocol, neither of which like to be changed much.

> so the sos language server might not be able to know the language of the content being passed

Assuming your files-on-disk can be statically analyzed by `sos-language-server`: the way it would [work](https://jupyterlab-lsp.readthedocs.io/en/latest/Architecture.html) for a "pure" language server today:

- user installs `jupyter-lsp` and `sos-language-server`
   - `sos-language-server`registers itself for whatever file extensions, mime types, and codemirror modes you created for the language `sos`: 
      - we support `traitlets` (e.g. `jupyter_notebook_config.json`) and `setuptools` `entry_points`
- `jupyter-lsp`, would advertise the `sos` spec on its REST API
-  when a `sos` kernel session gets started, finding the `sos` declaration `jupyterlab-lsp` would open a new websocket for `sos`, to be used for all `sos` documents
   - `jupyter-lsp` would start `sos-language-server`
     - we presently support stdio, but need to add TCP (e.g. https://github.com/krassowski/jupyterlab-lsp/issues/184#issuecomment-625798784)
- `jupyterlab-lsp` would start the LSP session with `initialize`
   - `jupyter-lsp` would proxy this and all messages _verbatim_ to `sos-language-server`
   - `sos-language-server`
- `jupyterlab-lsp` would finish setup with `configuration/didChange` (#245), `textDocument/didOpen`, etc.
   - `sos-language-server` would:
     - parse the `sos` syntax (with access to the whole file)
     - determine which _actual_ language server should be started/configured
       - hopefully being able to reuse the configuration machinery from `jupyter-lsp`
     - start and send `initialize` to each of _those_ languages
     - wait for all of _those_ to start up
     - transform the messages coming back, potentially sending it over the WebSocket
       - one of the first messages received is _usually_ `textDocument/publishDiagnostics`
     - finally, merge all _those_ responses, and send it back

> appears easier, and cleaner to implement this at the frontend level

That's your call: as _an extension_ to _an extension_ to _an client_, the stuff would "only" work with `jupyterlab-lsp`, and _only_ with the version of jupyterlab we support, and therefore would need to be upgraded in pretty tight lockstep to the Lab version. No doubt you could write your stuff in such a way that the "guts" could be used in another client.

> dynamically change the language of the kernel. I can work on a PR if this is allowed by the architecture, and acceptable to the team.

As I mentioned, have a look at #191. If, instead of _requiring_ hacking a bunch of typescript (which, yes, we should of course _allow_, expose, and dogfood to implement any of the below), `sos` could do one or more of:

- Put in A Folder some schema-constrained JSON, some nunjucks templates, or a portable grammar which gets exposed by `jupyter_lsp`
- propose and implement a Kernel comm target, e.g. `jupyter.lsp.transclusions` which `sos` can use

..to mostly-statically describe "ways to transform code and into what language". The kernel-based approach could potentially offer said code transformation dynamically. This would support these concepts in a way that `jupyterlab-lsp` would only be a _reference_ implementation, not _the only_ implementation.

**Comment by BoPeng** [comment]
@bollwyvl Thanks for all the info. Let me dive into language server (protocol and implementation) and source code of `jupyterlab-lsp` before getting back to you.

**Comment by krassowski** [comment]
@BoPeng just wanted to let you know that I worked hard on restructuring the source code to make it more pleasant to look at. Also, potentially of your interest could be the improved cell-level syntax highlighting that we added here: https://github.com/krassowski/jupyterlab-lsp/pull/319. Please let us know if you are still interested in working on ridging SoS with jupyterlab-lsp - we are always happy to help!

**Comment by BoPeng** [comment]
Yes, this is on my TODO list, even relatively high, but I am swamped with other obligations (covid related projects, not surprisingly) and have not been able to work on this.

**Comment by BoPeng** [comment]
I had another look at the problem and it is likely a sos language server as @bollwyvl suggested is the best way to proceed. It would be a larger project than what my current bandwidth allows so it will take a while for sos users to make use of language servers.

**Comment by krassowski** [comment]
Okay, instead of creating `sos-language-server`, why don't we just use per-cell language-server as we already do with cell magics for IPython? This should be simple to implement.

**Comment by westurner** [comment]
> [...] why don't we just use per-cell language-server as we already do with cell magics for IPython? This should be simple to implement.

Are there any obstacles?

**Comment by westurner** [comment]
jupyterlab/debugger could/should/must also support multi-language notebooks. Are there similarities in implementation of the multi-language abstractions for LSP and for jupyterlab/debugger support?

- https://github.com/jupyterlab/debugger
  - xeus-python is the only kernel that supports debugging so far
  - ipykernel may also be supported soon
    https://github.com/jupyterlab/debugger/issues/274

**Comment by BoPeng** [comment]
> Okay, instead of creating sos-language-server, why don't we just use per-cell language-server as we already do with cell magics for IPython? This should be simple to implement.

That will make things much easier for SoS. SoS currently uses `kernel` meta data to specify the kernel of each cell, but I am willing to change that to whatever will be used by jupyterlab-lsp.

BTW, congratulations on the merge of https://github.com/jupyter/enhancement-proposals/pull/72 !

**Comment by denvesi** [comment]
> Okay, instead of creating `sos-language-server`, why don't we just use per-cell language-server as we already do with cell magics for IPython? This should be simple to implement.

@krassowski I would be interested in implementing this. I am a student and currently writing my master thesis and the project I am working on would benefit from supporting language servers. Unfortunately, the current state of the LSP plugin (if I understand it correctly) doesn't fit our use case, because we use multiple languages in one notebook. Per-cell language servers would solve this issue, so I would like to contribute. Though I am not the most experienced developer and I need to get a bit more familiar with the existing code, so a little guidance or at least general idea on how to solve this would be very much appreciated. :)

**Comment by krassowski** [comment]
You are very welcome to do work on it. I will be available to help and guide you if you run into any problems, though I may have longer response time than usual as next two weeks are very busy for me. I will try write up something with references to the code over the weekend.

**Comment by denvesi** [comment]
Thanks! That sounds great! It may take some time, because I am just at the beginning of my thesis, but I will try my best. Some references would be very helpful indeed.
